# Generated by Django 3.1.3 on 2021-01-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pesan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dt_contact',
            },
        ),
        migrations.CreateModel(
            name='Komentarblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pesan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dt_komentarblog',
            },
        ),
        migrations.CreateModel(
            name='Komentarlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pesan', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dt_komentarlist',
            },
        ),
    ]
