# Generated by Django 3.1.3 on 2020-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=500)),
                ('image_about', models.ImageField(upload_to='img/')),
            ],
            options={
                'db_table': 'dt_about',
            },
        ),
    ]
