# Generated by Django 3.1.3 on 2020-12-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori_blog',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dt_kategori_blog',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('image_blog', models.ImageField(upload_to='blog/')),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.kategori_blog')),
            ],
            options={
                'db_table': 'dt_blog',
            },
        ),
    ]
