# Generated by Django 3.1.3 on 2020-12-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempat', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('image_gallery', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'db_table': 'dt_gallery',
            },
        ),
    ]
