# Generated by Django 3.1.3 on 2020-12-31 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dt_kategori',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('harga', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=500)),
                ('image_list', models.ImageField(upload_to='list_rental/')),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_rental.kategori')),
            ],
            options={
                'db_table': 'dt_list',
            },
        ),
    ]
